src/main/kotlin/com/beust/kobalt/Main.kt, src/main/kotlin/com/beust/kobalt/ProjectGenerator.kt, src/main/kotlin/com/beust/kobalt/maven/Pom.kt, src/main/resources/build-template.mustache, src/test/kotlin/com/beust/kobalt/maven/PomTest.kt, src/test/resources/pom.xml
=> maven pom importing

src/main/kotlin/com/beust/kobalt/ProjectGenerator.kt, src/main/kotlin/com/beust/kobalt/api/Kobalt.kt, src/main/kotlin/com/beust/kobalt/maven/Pom.kt, src/main/resources/build-template.mustache, src/test/kotlin/com/beust/kobalt/maven/PomTest.kt, src/test/resources/pom-norepositories-properties.xml
also, make sure repository urls end with "/"
=> import repositories from the pom

modules/wrapper/src/main/java/com/beust/kobalt/wrapper/Main.java
Fix fail at file/directories creation
Fix several exception during wrapper update 0.215 -> 0.246
Better error handling and resource management (For example we have to close output file if download failed as we will not be able to retry on windows.
=> Wrapper cleanup and fix

build.gradle
Now the project builds from command line and is correctly imported in IDEA
=> Fix build.gradle some more

src/main/kotlin/com/beust/kobalt/Variant.kt
=> Generate BuildConfig with android pacage id if possible

kobaltw, modules/wrapper/src/main/java/com/beust/kobalt/wrapper/Main.java
Fixes the error with incorrect line endings on unix systems
=> Always generate kobaltw file

src/main/kotlin/com/beust/kobalt/maven/DepFactory.kt, src/main/kotlin/com/beust/kobalt/maven/MavenId.kt, src/main/kotlin/com/beust/kobalt/maven/RepoFinder.kt, src/main/kotlin/com/beust/kobalt/maven/SimpleDep.kt, src/main/kotlin/com/beust/kobalt/misc/Versions.kt, src/test/kotlin/com/beust/kobalt/KobaltTest.kt, src/test/kotlin/com/beust/kobalt/maven/DependencyTest.kt, src/test/kotlin/com/beust/kobalt/maven/DownloadTest.kt, src/test/kotlin/com/beust/kobalt/maven/MavenIdTest.kt, src/test/kotlin/com/beust/kobalt/misc/VersionTest.kt
fixes #12.  adds support for version ranges
updates MavenId parsing to match gradle's parsing
=> fixes #12 -- adds support for version ranges

src/main/kotlin/com/beust/kobalt/plugin/publish/JCenterApi.kt, src/main/kotlin/com/beust/kobalt/plugin/publish/PublishPlugin.kt
* Use getNoThrows for org in local.properties
* Revert change that conflated username and org in JCenterApi.kt
=> fix org uploading

README.md
@cbeust 
- Add TravisCI build status to `README.md`
=> Add Travis CI build status to readme

kobalt/src/Build.kt, src/main/kotlin/com/beust/kobalt/plugin/publish/BintrayApi.kt, src/main/kotlin/com/beust/kobalt/plugin/publish/PublishPlugin.kt
tweak the output to reflect the current file being uploaded
=> retrofit the rest of the bintray calls.  automate package creation.

src/main/kotlin/com/beust/kobalt/plugin/publish/BintrayApi.kt
artifacts end up in the correct place now.
better progress output
=> corrected bintray urls

modules/kobalt-plugin-api/src/main/kotlin/com/beust/kobalt/api/Kobalt.kt, modules/kobalt-plugin-api/src/main/kotlin/com/beust/kobalt/internal/KobaltSettingsXml.kt, modules/kobalt-plugin-api/src/main/kotlin/com/beust/kobalt/maven/Http.kt, modules/kobalt-plugin-api/src/main/kotlin/com/beust/kobalt/maven/aether/Aether.kt, modules/kobalt-plugin-api/src/main/kotlin/com/beust/kobalt/misc/GithubApi2.kt, src/main/kotlin/com/beust/kobalt/app/MainModule.kt
* fix proxy resolution for artifact resolving: proxy resolution should not be dependant on KobaltContext
=> * fix proxy resolution for artifact resolving: proxy resolution should not be dependant on KobaltContext

src/main/kotlin/com/beust/kobalt/Main.kt, src/main/kotlin/com/beust/kobalt/app/remote/KobaltServer.kt, src/main/kotlin/com/beust/kobalt/app/remote/ProcessUtil.kt
It was only using the default port whenever available.
=> KobaltServer now uses the port specified in the command line argument

src/test/kotlin/com/beust/kobalt/internal/TaskManagerTest.kt
@cbeust 
Forgot to push everything.
=> solve older tests

modules/kobalt-plugin-api/src/main/kotlin/com/beust/kobalt/maven/LocalRepo.kt, modules/kobalt-plugin-api/src/main/kotlin/com/beust/kobalt/maven/MavenId.kt, modules/kobalt-plugin-api/src/main/kotlin/com/beust/kobalt/maven/PomGenerator.kt
Solves issue: https://github.com/cbeust/kobalt/issues/190
=> Add classifier to MavenId

kobaltw.bat
=> * fix wrapper execution

dist/kobaltw.bat
=> fixed wrapper path in dist/kobaltw.bat

modules/kobalt-plugin-api/src/main/kotlin/com/beust/kobalt/archive/Archives.kt
the time stamps of the included jars and classes folders of other projects were not checked
=> fixed incremantal building of fatJar

modules/wrapper/src/main/java/com/beust/kobalt/wrapper/Main.java
=> Always generate the shebang line

modules/kobalt-plugin-api/src/main/kotlin/com/beust/kobalt/Args.kt, modules/kobalt-plugin-api/src/main/kotlin/com/beust/kobalt/Constants.kt, src/main/kotlin/com/beust/kobalt/Main.kt
=> Fix for --log -2 undocumented "quiet" feature.

kobaltw.bat
=> Validate current directory.

dist/kobaltw, kobaltw, modules/wrapper/src/main/java/com/beust/kobalt/wrapper/Main.java
Also now handles directory names with space in them.
=> Fixed kobaltw for TravisCI

modules/kobalt-plugin-api/src/main/kotlin/com/beust/kobalt/misc/KobaltLogger.kt
=> Switched from SimpleDateFormat to java.time

modules/kobalt-plugin-api/src/main/kotlin/com/beust/kobalt/internal/IncrementalManager.kt
You forgot `saveInputChecksum()` :wink:
=> Completed synchronization for the incremental manager.

modules/wrapper/src/main/java/com/beust/kobalt/wrapper/Config.java, modules/wrapper/src/main/java/com/beust/kobalt/wrapper/Main.java
Reading kobalt config file ~/.config/kobalt/settings.xml for HTTP proxy configuration using only Java standard lib.
=> Reading kobalt config file

modules/kobalt-plugin-api/src/main/kotlin/com/beust/kobalt/BuildScript.kt, modules/kobalt-plugin-api/src/main/kotlin/com/beust/kobalt/Directives.kt, modules/kobalt-plugin-api/src/main/kotlin/com/beust/kobalt/TestConfig.kt, modules/kobalt-plugin-api/src/main/kotlin/com/beust/kobalt/TestDirective.kt, modules/kobalt-plugin-api/src/main/kotlin/com/beust/kobalt/internal/GenericRunner.kt, src/main/kotlin/com/beust/kobalt/plugin/application/ApplicationPlugin.kt, src/main/kotlin/com/beust/kobalt/plugin/groovy/GroovyPlugin.kt, src/main/kotlin/com/beust/kobalt/plugin/java/JavaPlugin.kt, src/main/kotlin/com/beust/kobalt/plugin/kotlin/KotlinPlugin.kt, src/main/kotlin/com/beust/kobalt/plugin/packaging/PackagingPlugin.kt, src/main/kotlin/com/beust/kobalt/plugin/publish/PublishPlugin.kt
moved buildScript directive to Directives.kt
tagged BuildScriptConfig methods with @Directive
=> standardize BuildScript directives

src/main/kotlin/com/beust/kobalt/plugin/application/ApplicationPlugin.kt
i missed one earlier (maybe more).
=> standardize use of Directive (on methods/props)

modules/kobalt-plugin-api/src/main/kotlin/com/beust/kobalt/misc/KFiles.kt, src/main/kotlin/com/beust/kobalt/app/BuildFileCompiler.kt, src/main/kotlin/com/beust/kobalt/app/ParsedBuildFile.kt
* fix debug of Build.kt (do not rename original source file but use temporary folder instead)
=> * fix debug of Build.kt (do not rename original source file but use temporary folder instead)

modules/kobalt-plugin-api/src/main/kotlin/com/beust/kobalt/misc/Git.kt, src/main/kotlin/com/beust/kobalt/plugin/publish/PublishPlugin.kt
```
autoGitTag(false)
autoGitTag(tag = "v1.0")
autoGitTag(message = "Release $version")
autoGitTag(true, tag = "v1.0", message = "Version 1.0")
```
=> Added parameters to autoGitTag directive.

modules/kobalt-plugin-api/src/main/kotlin/com/beust/kobalt/misc/Git.kt, src/main/kotlin/com/beust/kobalt/plugin/publish/PublishPlugin.kt
My bad, I should've hard read the `git tag` docs more closely.
=> Added annotated directive to autoGitTag.

modules/kobalt-plugin-api/src/main/kotlin/com/beust/kobalt/misc/Git.kt, src/main/kotlin/com/beust/kobalt/plugin/publish/PublishPlugin.kt
Also removed unused parameter in `Git.kt`
=> Renamed auto paramter to enabled for autoGitTag directive.

kobalt/src/Build.kt, modules/kobalt-plugin-api/src/main/kotlin/com/beust/kobalt/internal/TestNgRunner.kt, src/main/resources/templates/build.mustache
=> Updated to testng 6.11

modules/kobalt-plugin-api/src/main/kotlin/com/beust/kobalt/maven/MavenId.kt, src/test/kotlin/com/beust/kobalt/maven/MavenIdTest.kt
=> file:// no longer considered valid maven coordinates

modules/kobalt-plugin-api/src/main/kotlin/com/beust/kobalt/internal/TestNgRunner.kt
=> Disabled TestNG output on --log 0

src/main/kotlin/com/beust/kobalt/app/UpdateKobalt.kt
=> Added support for --log 0 on --update

modules/kobalt-plugin-api/src/main/kotlin/com/beust/kobalt/misc/GithubApi2.kt
See https://github.com/cbeust/kobalt/pull/376#discussion_r109272822
=> Latest version check now defaults to current version.

modules/kobalt-plugin-api/src/main/kotlin/com/beust/kobalt/misc/GithubApi2.kt, src/main/kotlin/com/beust/kobalt/Main.kt
See https://github.com/cbeust/kobalt/pull/376#discussion_r109275115
=> Disable release version check if --dev

src/test/kotlin/com/beust/kobalt/VerifyKobaltZipTest.kt
=> Added test for CR line endings (DOS) in kobaltw.

modules/kobalt-plugin-api/src/main/kotlin/com/beust/kobalt/misc/JarUtils.kt
Locally, this reduces a run of kobaltw assemble --noIncremental
on the Kobalt codebase itself from 47 seconds to 25 seconds.
When JarInputStream.nextEntry is invoked, the stream sets its position
and length so that it can directly be used to read the underlying content
associated with the entry.  This avoids the need to call
JarFile(localFile).getInputStream(entry) and the cost associated with it.
addEntry has a slight change of semantics due to this change - it is now
the caller's responsibility to close the associated input stream.  The two
existing calls to the method were adjusted accordingly.
=> Reduce time spent in JAR/ZIP assembly.

modules/kobalt-plugin-api/src/main/kotlin/com/beust/kobalt/api/DependencyHolder.kt, modules/kobalt-plugin-api/src/main/kotlin/com/beust/kobalt/api/Project.kt, modules/kobalt-plugin-api/src/main/kotlin/com/beust/kobalt/internal/CompilerUtils.kt, modules/kobalt-plugin-api/src/main/kotlin/com/beust/kobalt/internal/JvmCompilerPlugin.kt, modules/kobalt-plugin-api/src/main/kotlin/com/beust/kobalt/maven/DependencyManager.kt, modules/kobalt-plugin-api/src/main/kotlin/com/beust/kobalt/maven/aether/Scope.kt
Please review. I _think_ I've covered everything, but I'm not 100% sure.
For example, I don't know if I need to do anything with:
https://github.com/cbeust/kobalt/blob/8aa122f00720aa4a16ab98b75f73ade723c16d00/modules/kobalt-plugin-api/src/main/kotlin/com/beust/kobalt/maven/aether/Filters.kt
=> Implementation of compileOnly

dist/kobaltw
=> Fix for OSX and calling outsite of residing directory

src/main/kotlin/com/beust/kobalt/plugin/packaging/PackagingPlugin.kt
=> Fixed config.taskName

modules/kobalt-plugin-api/src/main/kotlin/com/beust/kobalt/internal/JvmCompilerPlugin.kt, src/main/kotlin/com/beust/kobalt/plugin/java/JavadocConfig.kt
=> Made doc run after clean

src/main/kotlin/com/beust/kobalt/plugin/publish/BintrayApi.kt, src/main/kotlin/com/beust/kobalt/plugin/publish/PublishPlugin.kt
Also grab project description and url from pom, if not already specified.
See #419.
=> Fixed vcs_tag

modules/kobalt-plugin-api/src/main/kotlin/com/beust/kobalt/maven/Gpg.kt
Prettty straightforward, testing took longer, many platforms and options (Cygwin, Git Bash, etc.)
=> Added support for configuring gpg's via local.properties

src/main/kotlin/com/beust/kobalt/plugin/publish/BintrayApi.kt
=> Fixed repo name to use config param if available

kobalt/src/Build.kt, modules/kobalt-plugin-api/src/main/kotlin/com/beust/kobalt/Constants.kt, src/main/kotlin/com/beust/kobalt/plugin/kotlin/KotlinCompiler.kt
upgrades kotlin version to 1.1.51 with necessary changes to com.beust.kobalt.plugin.kotlin.KotlinCompiler
=> upgrade to kotlinc 1.1.51

modules/kobalt-plugin-api/src/main/kotlin/com/beust/kobalt/archive/Archives.kt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cbeust/kobalt/458)
=> Fixing the WAR filename could contain a `null` version #456

modules/kobalt-plugin-api/src/main/kotlin/com/beust/kobalt/archive/Archives.kt, src/main/kotlin/com/beust/kobalt/app/Profiles.kt
see https://github.com/cbeust/kobalt/commit/05f8e2f41acfe778eb52d7a697e9d02e4265afea#commitcomment-25415629
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cbeust/kobalt/462)
=> Code Review Changes

modules/kobalt-plugin-api/src/main/kotlin/com/beust/kobalt/misc/NewRunCommand.kt, src/main/kotlin/com/beust/kobalt/plugin/application/ApplicationPlugin.kt
Added the following parameters to the application plugin:
- ignoreErrorStream
- ignoreInputStream
- ignoreExitValue
=> Added ignore parameters to the application plugin.

modules/kobalt-plugin-api/src/main/kotlin/com/beust/kobalt/Args.kt, modules/wrapper/src/main/java/com/beust/kobalt/wrapper/Main.java, src/main/kotlin/com/beust/kobalt/Main.kt
=> No longer create directories, etc. when --help or --version are used.

modules/kobalt-plugin-api/src/main/kotlin/com/beust/kobalt/Args.kt, modules/kobalt-plugin-api/src/main/kotlin/com/beust/kobalt/maven/aether/Booter.kt, modules/kobalt-plugin-api/src/main/kotlin/com/beust/kobalt/maven/aether/KobaltMavenResolver.kt
For now it is ok. Maybe I will find a way to prevent a resolving of version ranges in the future.
=> Added "offline" argument to prevent remote resolving of dependencies

kobalt/src/Build.kt
fixes https://github.com/cbeust/kobalt/issues/496
=> upgrade guice to 4.2.2

kobalt/src/Build.kt
fixes https://github.com/cbeust/kobalt/issues/496
=> upgrade guava to 27.0.1 to resolve multimap ordering

modules/kobalt-plugin-api/src/main/kotlin/com/beust/kobalt/misc/NewRunCommand.kt
Previously, I submitted a PR that reported when the separate/external kotlinc process timed-out.  I mistakenly removed the exit-code check in that PR.  This restores that check.
=> extend timeout, restore process exitValue check
