cbeust/kobalt

kobaltw

The wrapper was looking for kobalt/wrapper/kobalt-wrapper.jar in the
current dir. It should actually be
$KOBALT_HOME/kobalt/wrapper/kobalt-wrapper.jar

Added $KOBALT_HOME/kobaltw to the wrapper

---

local.properties

This would allow the default project to build on gradle. At the same
time, since we have this file explicitly listed in .gitignore, this
will never get updated in ay PRs etc. This is just a simpel hack to
have the gradle builds passing.

Added a dummy local.properties file

---

kobalt/src/Build.kt

Currently `./kobaltw test` fails to compile tests on clean cloned repo due to missing directory. It causes testng to run no tests and kobalt reports success that is not correct.

Create directory before copy file in taskCopyVersionForWrapper

---

src/main/kotlin/com/beust/kobalt/plugin/publish/JCenterApi.kt
src/main/kotlin/com/beust/kobalt/plugin/publish/PublishPlugin.kt

This patch adds an optional `bintray.organization` to local.properties. 
```
bintray.user=asarazan
bintray.organization=levelmoney
bintray.apikey=...
```

Support for bintray Organizations

---

kobaltw
modules/wrapper/src/main/java/com/beust/kobalt/wrapper/Main.java

1. On linux 3rd party (non-repo) programs go to `/usr/local/`, their executables go (or are linked) to `/usr/local/bin/` I prefer linking, as it is much more maintainable.
2. `kobaltw` is too cumbersome to type, so it's `kw` for me. :)

Make kobaltw play nice when it's soft-linked (`ln -s`)

---

modules/kobalt-plugin-api/src/main/kotlin/com/beust/kobalt/misc/RunCommand.kt

Befor the fix the core read twise from the input stream, second time the stream was empty.
The affect was it that the output of any `run` command were not displayed in the console.

fixed an issue with RunCommand output

---

modules/kobalt-plugin-api/src/main/kotlin/com/beust/kobalt/api/Kobalt.kt
modules/kobalt-plugin-api/src/main/kotlin/com/beust/kobalt/internal/build/VersionCheckTimestampFile.kt
modules/kobalt-plugin-api/src/main/kotlin/com/beust/kobalt/misc/KobaltWrapperProperties.kt
src/main/kotlin/com/beust/kobalt/Main.kt
src/main/kotlin/com/beust/kobalt/app/UpdateKobalt.kt
src/main/resources/kobalt.properties

Adds a kobalt property `kobalt.version.check_timeout` which specifies a period of time to wait since the last kobalt version check befor the next one.
This removes a delay after each compilation (or any other command), because the network operations are performed only onece a `timeout`
I set the value to be `P1DT2H`, which corresponds to one day two hours (ISO-8601)
Note that the network timeout may be increased

ADD_newVersionCheck_timeout

---

modules/kobalt-plugin-api/src/main/kotlin/com/beust/kobalt/Plugins.kt

e.g. from IDE output folder, which makes plugin development easier
val p = plugins("my-plugin/classes")

support using plugins from directories

---

modules/kobalt-plugin-api/src/main/kotlin/com/beust/kobalt/internal/CompilerUtils.kt
modules/kobalt-plugin-api/src/main/kotlin/com/beust/kobalt/misc/Io.kt

I'm using central build output directory `<workspace>/build` (for all projects) by using `../` in `project.buildDirectory`:
```
val p1 = project {
name = "p1"
directory = "p1"
buildDirectory = "../build/p1"
}
```
This works fine except that Kobalt creates unused empty directories outside of the `<workspace>`directory.
This PR fixes this

fixed creation of classes directory at wrong parent

---

modules/kobalt-plugin-api/src/main/kotlin/com/beust/kobalt/JarGenerator.kt
modules/kobalt-plugin-api/src/main/kotlin/com/beust/kobalt/archive/Archives.kt
modules/kobalt-plugin-api/src/main/kotlin/com/beust/kobalt/misc/JarUtils.kt

E.g. building p2 (see below) failed with
`java.lang.AssertionError: File should exist: p2\p1\kobaltBuild\classes`
because `p2.directory is != "."`
```
val p1 = project {
name = "p1"
directory = name
}
val p2 = project(p1) {
name = "p2"
directory = name
assemble {
jar {
fatJar = true
}
}
}
```

fixed fatJar for projects in subdirectories that depend on other projects

---

modules/kobalt-plugin-api/src/main/kotlin/com/beust/kobalt/internal/TaskManager.kt

as discussed in issue #244: https://github.com/cbeust/kobalt/issues/244#issuecomment-225211217
All tests passed

no longer iterate over projects in TaskManager.installDynamicTasks()

---

src/main/kotlin/com/beust/kobalt/app/BuildFileCompiler.kt
src/main/kotlin/com/beust/kobalt/app/ParsedBuildFile.kt

When running kobalt it writes `kobalt123.kt` files to the temp folder, but never removes them.
Had already several thousand such files.

delete temporary "kobalt123.kt" files (in temp folder)

---

modules/kobalt-plugin-api/src/main/kotlin/com/beust/kobalt/maven/Md5.kt

If passing a file (e.g. a ZIP) to `Md5.toMd5Directories()` then it still used file content for the checksum. 
This PR changes that to using timestamps.

use timestamp checksum for files in `filesOrDirectories` parameter

---

src/main/kotlin/com/beust/kobalt/app/BuildScriptUtil.kt

fixes "ERROR wrong number of arguments" if adding property with getter to `Build.kt`. E.g.
```kobalt
val Project.libs: String
get() = "$directory/$buildDirectory/libs"
```

BuildScriptUtil.runBuildScriptJarFile(): do not invoke static getter that expects parameters

---

modules/wrapper/src/main/java/com/beust/kobalt/wrapper/Main.java

Previous fix #279 broke under Gygwin and MinGW.
Tested under Gygwin, MinGW and Linux. Feel free to test under OS X. It'll work. ;-)

Fix kobatlw shebang for Cygwin/MinGW.

---

dist/kobaltw
dist/kobaltw.bat
kobaltw
modules/wrapper/src/main/java/com/beust/kobalt/wrapper/Main.java

I changed #284 to handle Windows specifically. 
As discussed before, ``kobaltw.bat`` is now also created/installed by default.  It won't be overwritten if it already exists.
As also discussed, I switched ``kobaltw`` to the `bourne shell` as there is no longer anything specific to ``bash`` in it.

Batch file installation (Take 2)

---

modules/kobalt-plugin-api/src/main/kotlin/com/beust/kobalt/AsciiArt.kt
modules/kobalt-plugin-api/src/main/kotlin/com/beust/kobalt/misc/KobaltLogger.kt

Changed everything (log, error, warn, etc.) to use `CharSequence` instead of `String`, which allows `String` as well as `StringBuilder`, `StringBuffer`, etc. to be used in logging calls.
Additionally, I also noticed that `SimpleDateFormat.format()` was used in one of the classes that I modified (and potentially more). It is notorious for being **non-thread-safe**, and should not be used for logging.
Two options:
1. Wrap it in a thread-safe class.
2. Use `java.time.*` instead.
@cbeust Which do you prefer?

String changed to CharSequence in logging functions

---

modules/wrapper/src/main/java/com/beust/kobalt/wrapper/Main.java

Not sure about log level in case of NumberFormatException for the port number.

Added use of proxy as set by env variable 'http_proxy'

---

modules/kobalt-plugin-api/src/main/kotlin/com/beust/kobalt/misc/Git.kt

jGIt would not tag and complain:
`***** WARNING Unannotated tags cannot have a message or tagger`
whenever `setAnnotated(false)`

Fixed jGit complaining and not tagging if setAnnotated(false)

---

dist/kobaltw
modules/wrapper/src/main/java/com/beust/kobalt/wrapper/Main.java

So that `kobaltw` can be used as a symlink. eg:
```
ln -s /usr/local/share/kobalt/bin/kobaltw /usr/local/bin/
```
or even has a local installation:
```
ln -s ~/kobalt-1.0.20/bin/kobaltw ~/bin
```
No need to mess around with temporarily exporting paths, etc. I suspect `brew` does something similar.
With that in mind, the manual installation instructions could be changed to:
```
cd yourLocation
unzip kobalt-xxx.zip
cd kobalt-xxx
ln -s bin/kobaltw /usr/local/bin
```
or something of the sort.

Properly handle symlink

---

modules/kobalt-plugin-api/src/main/kotlin/com/beust/kobalt/misc/GithubApi2.kt

See https://github.com/cbeust/kobalt/issues/373. Please review.
One could argue that the timing should be configurable, or at least overwritable. Thoughts?

Only check latest release version number on GitHub every 10 minutes

---

src/test/kotlin/com/beust/kobalt/VerifyKobaltZipTest.kt

Fix for #401 
Unfortunately, there is no way determine if a file is executable on Windows, it assumes that any file your own is executable. I'm displaying a warning in that case (which might be overkill), but it will work on MacOS, Linux, etc.
I've looked in ways of determining if a `zipEntry` is executable, no luck there. I've even looked at `ACL` under Windows, no go either.

Added test to check if kobaltw is executable (*nix only.)

---

modules/wrapper/src/main/java/com/beust/kobalt/wrapper/Main.java

Fix #401 and should be closed.

Made sure kobaltw (dist) is executable on non-Windows platforms.

---

modules/kobalt-plugin-api/src/main/kotlin/com/beust/kobalt/misc/KobaltLogger.kt

Fix for #420 `warn()` issue.
Notice that the implementation is identical to `error()` which did things _correctly_.

Made warn() work like error() with provided message

---

src/main/kotlin/com/beust/kobalt/plugin/java/JavaPlugin.kt
src/main/kotlin/com/beust/kobalt/plugin/java/JavadocConfig.kt

There's an issue with the way Kobalt launches the `javadoc` executable when using the `-link` option.
It is used to create links to existing javadoc-generated documentation of external referenced classes.
You can run the `main` routine of the `JavadocConfig` class, and see that everything works like it should that way.
To produce the error add the following to your build file:
```
javadoc {
quiet = false
verbose = true
links("http://docs.oracle.com/javase/8/docs/api/")
}
```
```
./kobaltw clean doc --log 2
```
You'll get the following:
```
Constructing Javadoc information...
java.lang.IllegalArgumentException: protocol = http host = null
at sun.net.spi.DefaultProxySelector.select(DefaultProxySelector.java:176)
at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.j …
```

Implemented javadoc options

---

src/main/kotlin/com/beust/kobalt/plugin/apt/AptPlugin.kt

As discussed, this reverts to the previous `apt` implementation behavior. It does not affect `kapt` at all, and passed all of my tests with `semver` and `version-processor`.
The reason the `sources` directory was added to path is because you used the same directory creation function (`generatedSources`) for both `kapt` and `apt`. While `kapt` needs a few directories, `apt` doesn't.
As before, generated code is placed in `generated/source/apt`, and no longer in `generated/source/apt/sources/`.

Removed sources directory from apt generated directory path

---

modules/kobalt-plugin-api/src/main/kotlin/com/beust/kobalt/misc/Git.kt
src/main/kotlin/com/beust/kobalt/plugin/publish/PublishPlugin.kt

Not change to current behavior, just allowing to turn off auto-pushing the tag.

Added push parameter to autoGitTag

---

modules/kobalt-plugin-api/src/main/kotlin/com/beust/kobalt/Jvm.kt

The problem was that getting `javaHome` always return the value of `_javaHome`, so trying to set it is useless:
```kotlin
override var javaHome: File? = null
get() = _javaHome!!
```
To test with the previous version, simply set your JAVA_HOME to a JRE instead of JDK location. Tools.jar will not be found. For example:
```
export JAVA_HOME="C:\Program Files\Java\jre1.8.0_151"
```

Fixed finding tools.jar under Windows when JAVA_HOME is set to JRE.

---

modules/kobalt-plugin-api/src/main/kotlin/com/beust/kobalt/internal/KotlinJarFiles.kt
modules/kobalt-plugin-api/src/main/kotlin/com/beust/kobalt/misc/NewRunCommand.kt
src/main/kotlin/com/beust/kobalt/app/kotlin/KotlinTemplateGenerator.kt
src/main/kotlin/com/beust/kobalt/plugin/kotlin/KotlinPlugin.kt
src/main/resources/kobalt.properties
src/main/resources/templates/idea/KotlinJavaRuntime.xml

- extend external compiler timeout to 2min, logs clear error when timeout happens
- don't add kotlin-runtime jar to classpath (does not exist in kotlin 1.3.10)

Improve external compiler invocation
